import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import { Toaster } from "@/components/ui/toaster";
import SessionWrapper from "./SessionWrapper";
import Chat from "@/components/shared/chat/Chat";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Level App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionWrapper>
          <Navbar />
          {children}
          <Chat />
          <Toaster />
        </SessionWrapper>
      </body>
    </html>
  );
}
